name: ulearning_app_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  control_style: ^0.1.0
  flutter_svg: ^2.0.17
  flutter_spinkit: ^5.2.1
  fl_chart: ^0.70.2
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.1.2
  go_router: ^14.7.2
  url_strategy: ^0.3.0
  cloud_firestore: ^5.6.3
  http: ^1.3.0
  shared_preferences: ^2.5.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
  fonts:
      - family: "Nunito"
        fonts: 
          - asset: assets/fonts/Nunito/static/Nunito-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/Nunito/static/Nunito-Light.ttf
            weight: 300
          - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
            weight: 400
          - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
            weight: 500
          - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
            weight: 700
          - asset: assets/fonts/Nunito/static/Nunito-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/Nunito/static/Nunito-Black.ttf
            weight: 900

          - asset: assets/fonts/Nunito/static/Nunito-ExtraLightItalic.ttf
            style: italic
            weight: 200
          - asset: assets/fonts/Nunito/static/Nunito-LightItalic.ttf
            style: italic
            weight: 300
          - asset: assets/fonts/Nunito/static/Nunito-Italic.ttf
            style: italic
            weight: 400
          - asset: assets/fonts/Nunito/static/Nunito-MediumItalic.ttf
            style: italic
            weight: 500
          - asset: assets/fonts/Nunito/static/Nunito-SemiBoldItalic.ttf
            style: italic
            weight: 600
          - asset: assets/fonts/Nunito/static/Nunito-BoldItalic.ttf
            style: italic
            weight: 700
          - asset: assets/fonts/Nunito/static/Nunito-ExtraBoldItalic.ttf
            style: italic
            weight: 800
          - asset: assets/fonts/Nunito/static/Nunito-BlackItalic.ttf
            style: italic
            weight: 900